name: prayer_times_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_riverpod: ^2.6.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  geocoding: ^4.0.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_svg: ^2.2.1
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  flutter_animate: ^4.5.2
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
